
name: Dockerfile build and publish

on:
  workflow_dispatch:
    inputs: 
      show_message:
        description: "Log errors if tests fails"
        required: true
        default: "false"
        type: boolean

  workflow_dispatch:
    inputs: 
      show_message:
        description: "Write build version"
        required: true
        default: "false"
        type: boolean
      build_version:
        description: "Enter the build version (e.g., v1.0.0)"
        required: true
        default: "v1.0.0"
        
jobs:

  unittest:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Test with pytest
      run: |
        pytest
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
  
  error_log:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Failing step if show_message is 'false'
        run: |
          echo "Error has occurd" > error.log
          exit 1
        if: ${{ github.event.inputs.show_message == 'true' }}
        
      - name: Upload error log
        if: failure()
        uses: actions/upload-artifact@v3
        with: 
          name: error-log
          path: error.log

  build:

    runs-on: ubuntu-latest
    needs: unittest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_TIM_USERNAME}}
          password: ${{ secrets.DOCKER_TIM_PASSWORD}}

      - name: Build Docker image
        run: docker build -t projectbounce . 

      - name: Tag Docker image
        run: docker tag projectbounce ${{ secrets.DOCKER_TIM_USERNAME }}/projectbounce:latest

      - name: Tag Docker image version
        run: docker tag projectbounce ${{ secrets.DOCKER_TIM_USERNAME }}/projectbounce:${{ github.event.inputs.build_version }}

      - name: Push Docker image to Docker Hub
        run: docker push ${{ secrets.DOCKER_TIM_USERNAME }}/projectbounce:latest
      

